const placeholderImg = "https://picsum.photos/600/400?random";

const Courses = [
  {
    id: 1,
    title: "Big 1 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Pemasaran",
  },
  {
    id: 2,
    title: "Big 2 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Bisnis",
  },
  {
    id: 3,
    title: "Big 3 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Design",
  },
  {
    id: 4,
    title: "Big 4 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Design",
  },
  {
    id: 5,
    title: "Big 5 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Pengembangan Diri",
  },
  {
    id: 6,
    title: "Big 6 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Pengembangan Diri",
  },
  {
    id: 7,
    title: "Big 7 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Pengembangan Diri",
  },
  {
    id: 8,
    title: "Big 8 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Pemasaran",
  },
  {
    id: 9,
    title: "Big 9 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 300000,
    job: "Junior Developer",
    category: "Pemasaran",
  },
  {
    id: 10,
    title: "Big 10 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 200000,
    job: "Senior Developer",
    category: "Bisnis",
  },
  {
    id: 11,
    title: "Big 11 Auditor Financial Analyst",
    img: placeholderImg,
    teacher: "Jenna",
    price: 150000,
    job: "Junior Developer",
    category: "Pemasaran",
  },
];

export default Courses;
